//
//  EmbeddedContent.swift
//  ShadowWord
//

import Foundation

extension ContentService {
    static let embeddedContent = GameContent(categories: [
        // MARK: - Animals
        Category(
            name: "Animals",
            icon: "pawprint.fill",
            words: [
                WordItem(word: "Elephant", hint: "Has a trunk", difficulty: "easy"),
                WordItem(word: "Giraffe", hint: "Tall with spots", difficulty: "easy"),
                WordItem(word: "Penguin", hint: "Waddles on ice", difficulty: "easy"),
                WordItem(word: "Dolphin", hint: "Smart swimmer", difficulty: "easy"),
                WordItem(word: "Kangaroo", hint: "Hops and has pouch", difficulty: "easy"),
                WordItem(word: "Lion", hint: "King of jungle", difficulty: "easy"),
                WordItem(word: "Tiger", hint: "Striped cat", difficulty: "easy"),
                WordItem(word: "Zebra", hint: "Black and white stripes", difficulty: "easy"),
                WordItem(word: "Monkey", hint: "Loves bananas", difficulty: "easy"),
                WordItem(word: "Bear", hint: "Hibernates", difficulty: "easy"),
                WordItem(word: "Wolf", hint: "Howls at moon", difficulty: "medium"),
                WordItem(word: "Fox", hint: "Clever and red", difficulty: "medium"),
                WordItem(word: "Owl", hint: "Night hunter", difficulty: "medium"),
                WordItem(word: "Eagle", hint: "Sharp eyes", difficulty: "medium"),
                WordItem(word: "Shark", hint: "Ocean predator", difficulty: "medium"),
                WordItem(word: "Whale", hint: "Largest mammal", difficulty: "medium"),
                WordItem(word: "Octopus", hint: "Eight arms", difficulty: "medium"),
                WordItem(word: "Crocodile", hint: "Snapping jaws", difficulty: "medium"),
                WordItem(word: "Turtle", hint: "Carries home", difficulty: "medium"),
                WordItem(word: "Parrot", hint: "Colorful talker", difficulty: "medium"),
                WordItem(word: "Cheetah", hint: "Fastest land animal", difficulty: "hard"),
                WordItem(word: "Leopard", hint: "Spotted cat", difficulty: "hard"),
                WordItem(word: "Jaguar", hint: "Rainforest cat", difficulty: "hard"),
                WordItem(word: "Panther", hint: "Black big cat", difficulty: "hard"),
                WordItem(word: "Hyena", hint: "Laughing hunter", difficulty: "hard"),
                WordItem(word: "Gazelle", hint: "Swift runner", difficulty: "hard"),
                WordItem(word: "Antelope", hint: "African grazer", difficulty: "hard"),
                WordItem(word: "Bison", hint: "Buffalo cousin", difficulty: "hard"),
                WordItem(word: "Moose", hint: "Large deer", difficulty: "hard"),
                WordItem(word: "Elk", hint: "Antlered deer", difficulty: "hard")
            ],
            questionPairs: [
                QuestionPair(mainQuestion: "What animal would you want as a pet?", liarQuestion: "What animal scares you the most?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What animal is the cutest?", liarQuestion: "What animal is the ugliest?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What animal would win in a race?", liarQuestion: "What animal is the slowest?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What animal lives in the ocean?", liarQuestion: "What animal lives in the desert?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What animal can fly?", liarQuestion: "What animal can swim?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What animal is best for a zoo?", liarQuestion: "What animal belongs in the wild?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What animal is the strongest?", liarQuestion: "What animal is the weakest?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What animal makes the best mascot?", liarQuestion: "What animal would be worst as a mascot?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What animal is most intelligent?", liarQuestion: "What animal seems less smart?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What animal has the best defense?", liarQuestion: "What animal is most vulnerable?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What animal would survive longest alone?", liarQuestion: "What animal needs a pack to survive?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What animal is most misunderstood?", liarQuestion: "What animal has good reputation?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What animal adapts best to cities?", liarQuestion: "What animal needs wilderness?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What animal has changed the most over time?", liarQuestion: "What animal stayed the same?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What animal is friendliest to humans?", liarQuestion: "What animal avoids humans?", difficulty: "hard")
            ]
        ),
        
        // MARK: - Food & Drinks
        Category(
            name: "Food & Drinks",
            icon: "fork.knife",
            words: [
                WordItem(word: "Pizza", hint: "Italian favorite", difficulty: "easy"),
                WordItem(word: "Hamburger", hint: "Classic American", difficulty: "easy"),
                WordItem(word: "Ice Cream", hint: "Cold and sweet", difficulty: "easy"),
                WordItem(word: "Chocolate", hint: "Sweet treat", difficulty: "easy"),
                WordItem(word: "Coffee", hint: "Morning drink", difficulty: "easy"),
                WordItem(word: "Spaghetti", hint: "Long noodles", difficulty: "easy"),
                WordItem(word: "Sandwich", hint: "Between bread", difficulty: "easy"),
                WordItem(word: "Pancakes", hint: "Breakfast stack", difficulty: "easy"),
                WordItem(word: "Popcorn", hint: "Movie snack", difficulty: "easy"),
                WordItem(word: "Apple", hint: "Keeps doctor away", difficulty: "easy"),
                WordItem(word: "Sushi", hint: "Japanese rolls", difficulty: "medium"),
                WordItem(word: "Tacos", hint: "Mexican shells", difficulty: "medium"),
                WordItem(word: "Curry", hint: "Spicy dish", difficulty: "medium"),
                WordItem(word: "Ramen", hint: "Noodle soup", difficulty: "medium"),
                WordItem(word: "Croissant", hint: "French pastry", difficulty: "medium"),
                WordItem(word: "Steak", hint: "Grilled meat", difficulty: "medium"),
                WordItem(word: "Lasagna", hint: "Layered pasta", difficulty: "medium"),
                WordItem(word: "Cheesecake", hint: "Creamy dessert", difficulty: "medium"),
                WordItem(word: "Smoothie", hint: "Blended drink", difficulty: "medium"),
                WordItem(word: "Milkshake", hint: "Thick sweet drink", difficulty: "medium"),
                WordItem(word: "Paella", hint: "Spanish rice", difficulty: "hard"),
                WordItem(word: "Risotto", hint: "Creamy rice", difficulty: "hard"),
                WordItem(word: "Gnocchi", hint: "Potato pasta", difficulty: "hard"),
                WordItem(word: "Tiramisu", hint: "Coffee dessert", difficulty: "hard"),
                WordItem(word: "Bruschetta", hint: "Tomato bread", difficulty: "hard"),
                WordItem(word: "Falafel", hint: "Chickpea balls", difficulty: "hard"),
                WordItem(word: "Hummus", hint: "Chickpea dip", difficulty: "hard"),
                WordItem(word: "Pho", hint: "Vietnamese soup", difficulty: "hard"),
                WordItem(word: "Dim Sum", hint: "Chinese small plates", difficulty: "hard"),
                WordItem(word: "Tempura", hint: "Fried batter", difficulty: "hard")
            ],
            questionPairs: [
                QuestionPair(mainQuestion: "What food is best for breakfast?", liarQuestion: "What food is best for dinner?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What's your favorite dessert?", liarQuestion: "What dessert do you dislike?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What food is best at parties?", liarQuestion: "What food is bad at parties?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What drink is most refreshing?", liarQuestion: "What drink is too heavy?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What food is easiest to make?", liarQuestion: "What food takes longest to cook?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What food is best on a cold day?", liarQuestion: "What food is best on a hot day?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What food is most overrated?", liarQuestion: "What food is underrated?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What's the best comfort food?", liarQuestion: "What food is not comforting?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What cuisine is the best?", liarQuestion: "What cuisine is the most unusual?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What food is best for a date?", liarQuestion: "What food is worst for a date?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What food represents your personality?", liarQuestion: "What food is opposite of you?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What food would you eat every day?", liarQuestion: "What food would you never eat?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What food is most nostalgic?", liarQuestion: "What food has no memories for you?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What food would you cook for 100 people?", liarQuestion: "What food would be disaster to cook?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What expensive food is worth it?", liarQuestion: "What cheap food is best value?", difficulty: "hard")
            ]
        ),
        
        // MARK: - Sports
        Category(
            name: "Sports",
            icon: "sportscourt.fill",
            words: [
                WordItem(word: "Soccer", hint: "Kick the ball", difficulty: "easy"),
                WordItem(word: "Basketball", hint: "Shoot hoops", difficulty: "easy"),
                WordItem(word: "Tennis", hint: "Racket sport", difficulty: "easy"),
                WordItem(word: "Swimming", hint: "In the pool", difficulty: "easy"),
                WordItem(word: "Running", hint: "Track event", difficulty: "easy"),
                WordItem(word: "Baseball", hint: "Bat and ball", difficulty: "easy"),
                WordItem(word: "Football", hint: "Touchdown sport", difficulty: "easy"),
                WordItem(word: "Golf", hint: "Hole in one", difficulty: "easy"),
                WordItem(word: "Volleyball", hint: "Net sport", difficulty: "easy"),
                WordItem(word: "Skiing", hint: "Snow slopes", difficulty: "easy"),
                WordItem(word: "Boxing", hint: "Fighting ring", difficulty: "medium"),
                WordItem(word: "Wrestling", hint: "Mat sport", difficulty: "medium"),
                WordItem(word: "Surfing", hint: "Ride waves", difficulty: "medium"),
                WordItem(word: "Cycling", hint: "Bike race", difficulty: "medium"),
                WordItem(word: "Gymnastics", hint: "Flips and bars", difficulty: "medium"),
                WordItem(word: "Hockey", hint: "Ice rink", difficulty: "medium"),
                WordItem(word: "Rugby", hint: "Oval ball", difficulty: "medium"),
                WordItem(word: "Cricket", hint: "Wickets", difficulty: "medium"),
                WordItem(word: "Archery", hint: "Bow and arrow", difficulty: "medium"),
                WordItem(word: "Fencing", hint: "Sword sport", difficulty: "medium"),
                WordItem(word: "Lacrosse", hint: "Net sticks", difficulty: "hard"),
                WordItem(word: "Polo", hint: "Horse sport", difficulty: "hard"),
                WordItem(word: "Curling", hint: "Ice stones", difficulty: "hard"),
                WordItem(word: "Bobsled", hint: "Ice track", difficulty: "hard"),
                WordItem(word: "Biathlon", hint: "Ski and shoot", difficulty: "hard"),
                WordItem(word: "Triathlon", hint: "Three sports", difficulty: "hard"),
                WordItem(word: "Decathlon", hint: "Ten events", difficulty: "hard"),
                WordItem(word: "Handball", hint: "Indoor throw", difficulty: "hard"),
                WordItem(word: "Badminton", hint: "Shuttlecock", difficulty: "hard"),
                WordItem(word: "Squash", hint: "Indoor racket", difficulty: "hard")
            ],
            questionPairs: [
                QuestionPair(mainQuestion: "What sport is most fun to watch?", liarQuestion: "What sport is boring to watch?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What sport is best for exercise?", liarQuestion: "What sport is least active?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What sport would you try?", liarQuestion: "What sport would you never try?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What sport has the best athletes?", liarQuestion: "What sport requires least skill?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What team sport is best?", liarQuestion: "What solo sport is best?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What sport is most dangerous?", liarQuestion: "What sport is safest?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What sport requires most practice?", liarQuestion: "What sport is easy to learn?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What Olympic sport is best?", liarQuestion: "What sport shouldn't be Olympic?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What sport is best in summer?", liarQuestion: "What sport is best in winter?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What sport has best fans?", liarQuestion: "What sport has worst fans?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What sport will grow most popular?", liarQuestion: "What sport is dying out?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What sport best builds character?", liarQuestion: "What sport is just for fun?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What sport is most underrated?", liarQuestion: "What sport is overrated?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What sport would you coach?", liarQuestion: "What sport you can't explain?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What sport has best equipment?", liarQuestion: "What sport needs no equipment?", difficulty: "hard")
            ]
        ),
        
        // MARK: - Movies & TV
        Category(
            name: "Movies & TV",
            icon: "film.fill",
            words: [
                WordItem(word: "Comedy", hint: "Makes you laugh", difficulty: "easy"),
                WordItem(word: "Horror", hint: "Scary films", difficulty: "easy"),
                WordItem(word: "Action", hint: "Explosions", difficulty: "easy"),
                WordItem(word: "Romance", hint: "Love stories", difficulty: "easy"),
                WordItem(word: "Animation", hint: "Cartoon movies", difficulty: "easy"),
                WordItem(word: "Documentary", hint: "Real stories", difficulty: "easy"),
                WordItem(word: "Musical", hint: "Singing films", difficulty: "easy"),
                WordItem(word: "Western", hint: "Cowboys", difficulty: "easy"),
                WordItem(word: "Fantasy", hint: "Magic worlds", difficulty: "easy"),
                WordItem(word: "Thriller", hint: "Suspenseful", difficulty: "easy"),
                WordItem(word: "Sitcom", hint: "TV comedy", difficulty: "medium"),
                WordItem(word: "Drama", hint: "Emotional story", difficulty: "medium"),
                WordItem(word: "Reality TV", hint: "Unscripted shows", difficulty: "medium"),
                WordItem(word: "Talk Show", hint: "Interview format", difficulty: "medium"),
                WordItem(word: "Game Show", hint: "Win prizes", difficulty: "medium"),
                WordItem(word: "Soap Opera", hint: "Daily drama", difficulty: "medium"),
                WordItem(word: "Mini Series", hint: "Limited episodes", difficulty: "medium"),
                WordItem(word: "Anthology", hint: "Different stories", difficulty: "medium"),
                WordItem(word: "Sci-Fi", hint: "Space and future", difficulty: "medium"),
                WordItem(word: "Mystery", hint: "Whodunit", difficulty: "medium"),
                WordItem(word: "Film Noir", hint: "Dark detective", difficulty: "hard"),
                WordItem(word: "Mockumentary", hint: "Fake documentary", difficulty: "hard"),
                WordItem(word: "Biopic", hint: "Life story", difficulty: "hard"),
                WordItem(word: "Indie Film", hint: "Independent", difficulty: "hard"),
                WordItem(word: "Blockbuster", hint: "Big budget", difficulty: "hard"),
                WordItem(word: "Cult Classic", hint: "Devoted fans", difficulty: "hard"),
                WordItem(word: "Sequel", hint: "Part two", difficulty: "hard"),
                WordItem(word: "Prequel", hint: "Before original", difficulty: "hard"),
                WordItem(word: "Remake", hint: "New version", difficulty: "hard"),
                WordItem(word: "Spin-off", hint: "Side story", difficulty: "hard")
            ],
            questionPairs: [
                QuestionPair(mainQuestion: "What genre is the best?", liarQuestion: "What genre is the worst?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What movie would you watch twice?", liarQuestion: "What movie would you never rewatch?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What's best for movie night?", liarQuestion: "What's worst for movie night?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What makes a good villain?", liarQuestion: "What makes a good hero?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What movie makes you cry?", liarQuestion: "What movie makes you laugh?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What's the best movie decade?", liarQuestion: "What decade had worst movies?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What show is worth binging?", liarQuestion: "What show is not worth it?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What movie is underrated?", liarQuestion: "What movie is overrated?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What actor is most versatile?", liarQuestion: "What actor always plays same role?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What ending was most satisfying?", liarQuestion: "What ending was disappointing?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What movie changed cinema?", liarQuestion: "What movie had no impact?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What remake was better than original?", liarQuestion: "What remake was unnecessary?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What should get a sequel?", liarQuestion: "What should never get sequel?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What director has best style?", liarQuestion: "What director is overrated?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What soundtrack is iconic?", liarQuestion: "What movie has forgettable music?", difficulty: "hard")
            ]
        ),
        
        // MARK: - Countries & Places
        Category(
            name: "Countries & Places",
            icon: "globe.americas.fill",
            words: [
                WordItem(word: "Paris", hint: "City of love", difficulty: "easy"),
                WordItem(word: "Tokyo", hint: "Japan capital", difficulty: "easy"),
                WordItem(word: "New York", hint: "Big Apple", difficulty: "easy"),
                WordItem(word: "London", hint: "Big Ben", difficulty: "easy"),
                WordItem(word: "Rome", hint: "Ancient empire", difficulty: "easy"),
                WordItem(word: "Sydney", hint: "Opera house", difficulty: "easy"),
                WordItem(word: "Dubai", hint: "Tall towers", difficulty: "easy"),
                WordItem(word: "Cairo", hint: "Pyramids nearby", difficulty: "easy"),
                WordItem(word: "Barcelona", hint: "Spanish coast", difficulty: "easy"),
                WordItem(word: "Amsterdam", hint: "Canals city", difficulty: "easy"),
                WordItem(word: "Singapore", hint: "City state", difficulty: "medium"),
                WordItem(word: "Bangkok", hint: "Thai capital", difficulty: "medium"),
                WordItem(word: "Istanbul", hint: "Two continents", difficulty: "medium"),
                WordItem(word: "Mumbai", hint: "Bollywood", difficulty: "medium"),
                WordItem(word: "Berlin", hint: "German capital", difficulty: "medium"),
                WordItem(word: "Moscow", hint: "Red Square", difficulty: "medium"),
                WordItem(word: "Rio", hint: "Carnival city", difficulty: "medium"),
                WordItem(word: "Toronto", hint: "CN Tower", difficulty: "medium"),
                WordItem(word: "Seoul", hint: "K-pop home", difficulty: "medium"),
                WordItem(word: "Vienna", hint: "Music city", difficulty: "medium"),
                WordItem(word: "Prague", hint: "Castle city", difficulty: "hard"),
                WordItem(word: "Budapest", hint: "Pearl of Danube", difficulty: "hard"),
                WordItem(word: "Lisbon", hint: "Portugal capital", difficulty: "hard"),
                WordItem(word: "Athens", hint: "Ancient Greece", difficulty: "hard"),
                WordItem(word: "Marrakech", hint: "Moroccan city", difficulty: "hard"),
                WordItem(word: "Hanoi", hint: "Vietnam capital", difficulty: "hard"),
                WordItem(word: "Taipei", hint: "Taiwan capital", difficulty: "hard"),
                WordItem(word: "Buenos Aires", hint: "Tango city", difficulty: "hard"),
                WordItem(word: "Cape Town", hint: "Table Mountain", difficulty: "hard"),
                WordItem(word: "Reykjavik", hint: "Iceland capital", difficulty: "hard")
            ],
            questionPairs: [
                QuestionPair(mainQuestion: "Where would you vacation?", liarQuestion: "Where would you never visit?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What city is most beautiful?", liarQuestion: "What city is most crowded?", difficulty: "easy"),
                QuestionPair(mainQuestion: "Where has best food?", liarQuestion: "Where has strange food?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What country is most welcoming?", liarQuestion: "What country is hardest to visit?", difficulty: "easy"),
                QuestionPair(mainQuestion: "Where would you live abroad?", liarQuestion: "Where could you never live?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What place is most romantic?", liarQuestion: "What place is least romantic?", difficulty: "medium"),
                QuestionPair(mainQuestion: "Where has best nightlife?", liarQuestion: "Where is too quiet?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What country has best nature?", liarQuestion: "What country is too urban?", difficulty: "medium"),
                QuestionPair(mainQuestion: "Where is most underrated?", liarQuestion: "Where is overrated?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What place is most historic?", liarQuestion: "What place is too modern?", difficulty: "medium"),
                QuestionPair(mainQuestion: "Where would you retire?", liarQuestion: "Where is too expensive to retire?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What place changed you most?", liarQuestion: "What place left no impression?", difficulty: "hard"),
                QuestionPair(mainQuestion: "Where has best public transit?", liarQuestion: "Where needs better transit?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What emerging destination is hot?", liarQuestion: "What destination is past its peak?", difficulty: "hard"),
                QuestionPair(mainQuestion: "Where would you send exchange student?", liarQuestion: "Where is too challenging for students?", difficulty: "hard")
            ]
        ),
        
        // MARK: - Everyday Objects
        Category(
            name: "Everyday Objects",
            icon: "bag.fill",
            words: [
                WordItem(word: "Phone", hint: "Always in pocket", difficulty: "easy"),
                WordItem(word: "Keys", hint: "Opens locks", difficulty: "easy"),
                WordItem(word: "Wallet", hint: "Holds money", difficulty: "easy"),
                WordItem(word: "Watch", hint: "Tells time", difficulty: "easy"),
                WordItem(word: "Glasses", hint: "Helps you see", difficulty: "easy"),
                WordItem(word: "Umbrella", hint: "For rain", difficulty: "easy"),
                WordItem(word: "Backpack", hint: "Carries stuff", difficulty: "easy"),
                WordItem(word: "Headphones", hint: "For music", difficulty: "easy"),
                WordItem(word: "Laptop", hint: "Portable computer", difficulty: "easy"),
                WordItem(word: "Charger", hint: "Powers devices", difficulty: "easy"),
                WordItem(word: "Mirror", hint: "See reflection", difficulty: "medium"),
                WordItem(word: "Pillow", hint: "For sleeping", difficulty: "medium"),
                WordItem(word: "Blanket", hint: "Keeps warm", difficulty: "medium"),
                WordItem(word: "Lamp", hint: "Gives light", difficulty: "medium"),
                WordItem(word: "Clock", hint: "On the wall", difficulty: "medium"),
                WordItem(word: "Remote", hint: "Changes channel", difficulty: "medium"),
                WordItem(word: "Scissors", hint: "For cutting", difficulty: "medium"),
                WordItem(word: "Stapler", hint: "Office tool", difficulty: "medium"),
                WordItem(word: "Tape", hint: "Sticks things", difficulty: "medium"),
                WordItem(word: "Brush", hint: "For hair", difficulty: "medium"),
                WordItem(word: "Coaster", hint: "Protects tables", difficulty: "hard"),
                WordItem(word: "Bookmark", hint: "Saves page", difficulty: "hard"),
                WordItem(word: "Corkscrew", hint: "Opens bottles", difficulty: "hard"),
                WordItem(word: "Whisk", hint: "Kitchen tool", difficulty: "hard"),
                WordItem(word: "Spatula", hint: "Flips food", difficulty: "hard"),
                WordItem(word: "Plunger", hint: "Bathroom tool", difficulty: "hard"),
                WordItem(word: "Flashlight", hint: "Portable light", difficulty: "hard"),
                WordItem(word: "Thermos", hint: "Keeps drinks hot", difficulty: "hard"),
                WordItem(word: "Lint Roller", hint: "Removes fuzz", difficulty: "hard"),
                WordItem(word: "Shoehorn", hint: "Helps with shoes", difficulty: "hard")
            ],
            questionPairs: [
                QuestionPair(mainQuestion: "What can't you leave home without?", liarQuestion: "What do you always forget?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What object do you use most?", liarQuestion: "What object do you rarely use?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What makes life easier?", liarQuestion: "What is unnecessarily complicated?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What would you upgrade first?", liarQuestion: "What doesn't need upgrading?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What do you wish you had?", liarQuestion: "What do you have too many of?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What's the best invention?", liarQuestion: "What invention is useless?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What do you always lose?", liarQuestion: "What do you always find?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What's most satisfying to use?", liarQuestion: "What's frustrating to use?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What do kids today need?", liarQuestion: "What did kids have before?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What's worth spending money on?", liarQuestion: "What's a waste of money?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What will be obsolete in 10 years?", liarQuestion: "What will still be around forever?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What object has sentimental value?", liarQuestion: "What object is purely functional?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What should everyone own?", liarQuestion: "What do people waste money on?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What design is perfect?", liarQuestion: "What needs redesign?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What would you save in fire?", liarQuestion: "What is easily replaceable?", difficulty: "hard")
            ]
        ),
        
        // MARK: - Professions
        Category(
            name: "Professions",
            icon: "briefcase.fill",
            words: [
                WordItem(word: "Doctor", hint: "Heals people", difficulty: "easy"),
                WordItem(word: "Teacher", hint: "Educates kids", difficulty: "easy"),
                WordItem(word: "Chef", hint: "Cooks food", difficulty: "easy"),
                WordItem(word: "Pilot", hint: "Flies planes", difficulty: "easy"),
                WordItem(word: "Firefighter", hint: "Fights fires", difficulty: "easy"),
                WordItem(word: "Police", hint: "Law enforcement", difficulty: "easy"),
                WordItem(word: "Nurse", hint: "Hospital care", difficulty: "easy"),
                WordItem(word: "Lawyer", hint: "Legal expert", difficulty: "easy"),
                WordItem(word: "Artist", hint: "Creates art", difficulty: "easy"),
                WordItem(word: "Musician", hint: "Plays music", difficulty: "easy"),
                WordItem(word: "Architect", hint: "Designs buildings", difficulty: "medium"),
                WordItem(word: "Engineer", hint: "Builds things", difficulty: "medium"),
                WordItem(word: "Scientist", hint: "Research expert", difficulty: "medium"),
                WordItem(word: "Journalist", hint: "Writes news", difficulty: "medium"),
                WordItem(word: "Photographer", hint: "Takes photos", difficulty: "medium"),
                WordItem(word: "Veterinarian", hint: "Animal doctor", difficulty: "medium"),
                WordItem(word: "Dentist", hint: "Fixes teeth", difficulty: "medium"),
                WordItem(word: "Accountant", hint: "Handles money", difficulty: "medium"),
                WordItem(word: "Mechanic", hint: "Fixes cars", difficulty: "medium"),
                WordItem(word: "Electrician", hint: "Wires expert", difficulty: "medium"),
                WordItem(word: "Surgeon", hint: "Operating room", difficulty: "hard"),
                WordItem(word: "Psychologist", hint: "Mind expert", difficulty: "hard"),
                WordItem(word: "Pharmacist", hint: "Medicine expert", difficulty: "hard"),
                WordItem(word: "Paramedic", hint: "Emergency care", difficulty: "hard"),
                WordItem(word: "Translator", hint: "Languages", difficulty: "hard"),
                WordItem(word: "Diplomat", hint: "Government rep", difficulty: "hard"),
                WordItem(word: "Sommelier", hint: "Wine expert", difficulty: "hard"),
                WordItem(word: "Curator", hint: "Museum manager", difficulty: "hard"),
                WordItem(word: "Actuary", hint: "Risk analyst", difficulty: "hard"),
                WordItem(word: "Epidemiologist", hint: "Disease tracker", difficulty: "hard")
            ],
            questionPairs: [
                QuestionPair(mainQuestion: "What job would you want?", liarQuestion: "What job would you hate?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What job is most respected?", liarQuestion: "What job is underappreciated?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What job helps people most?", liarQuestion: "What job only helps yourself?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What job is hardest?", liarQuestion: "What job is easiest?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What job would kids want?", liarQuestion: "What job sounds boring to kids?", difficulty: "easy"),
                QuestionPair(mainQuestion: "What job will grow in demand?", liarQuestion: "What job will disappear?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What job pays too little?", liarQuestion: "What job pays too much?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What job is most stressful?", liarQuestion: "What job is most relaxing?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What job requires most creativity?", liarQuestion: "What job is most routine?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What job has best work-life balance?", liarQuestion: "What job takes over your life?", difficulty: "medium"),
                QuestionPair(mainQuestion: "What job makes biggest impact?", liarQuestion: "What job has least impact?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What job would you recommend?", liarQuestion: "What job would you warn against?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What job is most misunderstood?", liarQuestion: "What job is exactly as expected?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What job would you do for free?", liarQuestion: "What job needs higher pay?", difficulty: "hard"),
                QuestionPair(mainQuestion: "What unconventional job is cool?", liarQuestion: "What traditional job is stable?", difficulty: "hard")
            ]
        ),
        
        ] + additionalCategories)
}
